# Generated by Django 4.0.3 on 2022-03-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=1000)),
                ('discord_link', models.CharField(max_length=1000)),
                ('amount_of_invites', models.IntegerField()),
                ('verification_message', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_project', models.CharField(max_length=1000)),
            ],
        ),
    ]
