# Generated by Django 4.0.3 on 2022-03-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='current_user',
            field=models.CharField(default='admin', max_length=1000),
            preserve_default=False,
        ),
    ]
