# Generated by Django 4.0.3 on 2022-03-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_order_current_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_done',
            field=models.IntegerField(default=0),
        ),
    ]
