# Generated by Django 4.0.3 on 2022-05-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='current_user',
            field=models.CharField(default='admin', max_length=1000),
            preserve_default=False,
        ),
    ]
